from __future__ import annotations
from typing import Any, Protocol, Sequence
from ...api import Event, Task
class CalDAVAdapter(Protocol):
    def discover(self, base_url: str, credentials: Any) -> dict[str,Any]: ...
    def collections(self) -> Sequence[dict[str,Any]]: ...
    def get_task(self, task_id: str) -> Task: ...
    def list_tasks(self, **filters: Any) -> Sequence[Task]: ...
    def create_task(self, task: Task) -> Task: ...
    def update_task(self, task_id: str, changes: dict[str,Any], *, etag: str|None=None) -> Task: ...
    def delete_task(self, task_id: str, *, etag: str|None=None) -> None: ...
    def get_event(self,event_id:str)->Event: ...
    def list_events(self,**filters:Any)->Sequence[Event]: ...
    def create_event(self,event:Event)->Event: ...
    def update_event(self,event_id:str,changes:dict[str,Any],*,etag:str|None=None)->Event: ...
    def delete_event(self,event_id:str,*,etag:str|None=None)->None: ...
