from typing import Protocol
class WordPressAdapter(Protocol):
    def create_log(self,text,**metadata): ...
    def create_post(self,*a,**k): ...
    def update_post(self,*a,**k): ...
    def test_connection(self): ...
