"""Default stable Public Python API.

``caldav_assistant.api`` intentionally re-exports the current stable API version.
Extensions that require an explicit long-term version boundary may import the
same names from ``caldav_assistant.api.v1``.
"""
from .v1 import (
    ActionResult,
    Activity,
    ActivityAPI,
    Agenda,
    AgendaAPI,
    AgendaItem,
    AmbiguousError,
    AssistantContext,
    CalDAVAssistantError,
    CommandsAPI,
    ConflictError,
    Event,
    EventBus,
    EventsAPI,
    ExtensionError,
    HookDispatchReport,
    HookEvent,
    HookFailure,
    HookHandle,
    NotFoundError,
    NotificationsAPI,
    PermissionError,
    Reminder,
    RemindersAPI,
    SessionAPI,
    SettingsAPI,
    Task,
    TasksAPI,
    TemporalAPI,
    UIAPI,
    UnavailableError,
    ValidationError,
    WordPressAPI,
    emit,
    get_event_bus,
    off,
    on,
    unregister_owner,
)

__all__ = [
    "AssistantContext",
    "Task",
    "Event",
    "Agenda",
    "AgendaItem",
    "Reminder",
    "Activity",
    "ActionResult",
    "TasksAPI",
    "EventsAPI",
    "AgendaAPI",
    "RemindersAPI",
    "NotificationsAPI",
    "WordPressAPI",
    "UIAPI",
    "TemporalAPI",
    "CommandsAPI",
    "ActivityAPI",
    "SettingsAPI",
    "SessionAPI",
    "CalDAVAssistantError",
    "NotFoundError",
    "AmbiguousError",
    "ValidationError",
    "ConflictError",
    "UnavailableError",
    "PermissionError",
    "ExtensionError",
    "EventBus",
    "HookDispatchReport",
    "HookEvent",
    "HookFailure",
    "HookHandle",
    "emit",
    "get_event_bus",
    "off",
    "on",
    "unregister_owner",
]
