"""Default stable Public Python API.

``caldav_assistant.api`` intentionally re-exports the current stable API version.
Extensions that require an explicit long-term version boundary may import the
same names from ``caldav_assistant.api.v1``.
"""
from .v1 import (
    ActionResult,
    Activity,
    Agenda,
    AgendaItem,
    AmbiguousError,
    AssistantContext,
    CalDAVAssistantError,
    ConflictError,
    EventBus,
    HookDispatchReport,
    HookEvent,
    HookFailure,
    HookHandle,
    NotificationRequest,
    emit,
    get_event_bus,
    off,
    unregister_owner,
    Event,
    ExtensionError,
    NotFoundError,
    PermissionError,
    Reminder,
    Task,
    UnavailableError,
    ValidationError,
    on,
    reminder_rule,
)

__all__ = [
    "AssistantContext",
    "Task",
    "Event",
    "Agenda",
    "AgendaItem",
    "Reminder",
    "Activity",
    "ActionResult",
    "NotificationRequest",
    "reminder_rule",
    "CalDAVAssistantError",
    "NotFoundError",
    "AmbiguousError",
    "ValidationError",
    "ConflictError",
    "UnavailableError",
    "PermissionError",
    "ExtensionError",
    "EventBus",
    "HookDispatchReport",
    "HookEvent",
    "HookFailure",
    "HookHandle",
    "emit",
    "get_event_bus",
    "off",
    "on",
    "unregister_owner",
]
