from __future__ import annotations

from datetime import date, datetime, time
from typing import Any, Callable, Iterable, Mapping, ParamSpec, Sequence, TypeVar

from .api import ActionResult, Agenda, AgendaItem, Event, Reminder, Task

_P = ParamSpec("_P")
_R = TypeVar("_R")
_T = TypeVar("_T")


def command(
    name: str,
    *,
    aliases: Iterable[str] | None = ...,
    description: str = ...,
    metadata: Mapping[str, Any] | None = ...,
    override: bool = ...,
    allow_protected_override: bool = ...,
) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]: ...


def show(value: Any) -> None: ...


def tasks(**filters: Any) -> list[Task]: ...
def today_tasks(**filters: Any) -> list[Task]: ...
def overdue_tasks(**filters: Any) -> list[Task]: ...
def next_task(**options: Any) -> Task | None: ...
def find_task(query: str, **filters: Any) -> Task: ...


def events(**filters: Any) -> list[Event]: ...
def today_events(**filters: Any) -> list[Event]: ...
def next_event(**options: Any) -> Event | None: ...
def find_event(query: str, **filters: Any) -> Event: ...


def today() -> Agenda: ...
def agenda(days: int = ..., **filters: Any) -> Agenda: ...
def next(**options: Any) -> AgendaItem | None: ...


def add_task(summary: str, **fields: Any) -> ActionResult: ...
def edit_task(task: Task | str, **changes: Any) -> ActionResult | None: ...
def start(task: Task | str) -> ActionResult | None: ...
def pause(task: Task | str) -> ActionResult | None: ...
def resume(task: Task | str) -> ActionResult | None: ...
def complete(task: Task | str) -> ActionResult | None: ...
def remove(task: Task | Event | str) -> ActionResult | None: ...
def set_due(task: Task | str, due: Any) -> ActionResult | None: ...


def add_event(summary: str, **fields: Any) -> ActionResult: ...
def edit_event(event: Event | str, **changes: Any) -> ActionResult | None: ...
def remove_event(event: Event | str) -> ActionResult | None: ...


def parse_date(text: str, *, bias: str = ...) -> date: ...
def parse_datetime(text: str, *, bias: str = ...) -> datetime: ...
def parse_time(text: str) -> time: ...
def ask_date(prompt: str = ...) -> date | None: ...
def ask_time(prompt: str = ...) -> time | None: ...
def ask_datetime(prompt: str = ...) -> datetime | None: ...


def choose(items: Sequence[_T], title: str = ..., **options: Any) -> _T | None: ...
def choose_many(items: Sequence[_T], title: str = ..., **options: Any) -> list[_T]: ...
def confirm(text: str, **options: Any) -> bool: ...
def choose_task(**filters: Any) -> Task | None: ...
def choose_event(**filters: Any) -> Event | None: ...


def remind(title: str, when: Any, **options: Any) -> Reminder: ...
def notify(title: str, body: str = ..., actions: Any = ...) -> Any: ...
def snooze(reminder: Any, until: Any) -> Any: ...
def write_log(text: str, **metadata: Any) -> Any: ...
