"""Structural typing contracts for the stable v1 Object API.

These Protocols describe the public namespaces exposed by :class:`AssistantContext`.
They are intentionally interface-only: production services and CLI Runtime proxies
satisfy them structurally without importing or subclassing these types.

The main consumer is editor/static-analysis tooling (VS Code/Pylance, pyright, mypy)
for extension authors.  Runtime business behaviour remains owned by Core services.
"""
from __future__ import annotations

from datetime import date, datetime, time
from typing import Any, Callable, Mapping, Protocol, Sequence

from .models import ActionResult, Activity, Agenda, AgendaItem, Event, Reminder, Task


class TasksAPI(Protocol):
    def list(self, **filters: Any) -> list[Task]: ...
    def find(self, query: str, **filters: Any) -> Task: ...
    def get(self, task: Task | str) -> Task: ...
    def create(self, summary: Task | str, **fields: Any) -> ActionResult: ...
    def update(self, task: Task | str, **changes: Any) -> ActionResult: ...
    def complete(self, task: Task | str) -> ActionResult: ...
    def start(self, task: Task | str) -> ActionResult: ...
    def pause(self, task: Task | str) -> ActionResult: ...
    def resume(self, task: Task | str) -> ActionResult: ...
    def delete(self, task: Task | str) -> ActionResult: ...


class EventsAPI(Protocol):
    def list(self, **filters: Any) -> list[Event]: ...
    def find(self, query: str, **filters: Any) -> Event: ...
    def get(self, event: Event | str) -> Event: ...
    def create(self, summary: Event | str, **fields: Any) -> ActionResult: ...
    def update(self, event: Event | str, **changes: Any) -> ActionResult: ...
    def delete(self, event: Event | str) -> ActionResult: ...


class AgendaAPI(Protocol):
    def today(self) -> Agenda: ...
    def range(self, days: int = 1, **filters: Any) -> Agenda: ...
    def next(self, kind: str | None = None, **options: Any) -> AgendaItem | None: ...
    def overdue(self) -> list[Task]: ...


class RemindersAPI(Protocol):
    def list(self, **filters: Any) -> list[Reminder]: ...
    def create(self, title: str, when: Any, **options: Any) -> Reminder: ...
    def snooze(self, reminder: Reminder | str, until: Any) -> Any: ...
    def cancel(self, reminder: Reminder | str) -> Any: ...


class NotificationsAPI(Protocol):
    def send(self, title: str, body: str = "", actions: Any = None) -> Any: ...


class WordPressAPI(Protocol):
    def log(self, text: str, **metadata: Any) -> Any: ...
    def create_post(self, title: str, content: str = "", **metadata: Any) -> Any: ...
    def update_post(self, post_id: Any, **changes: Any) -> Any: ...
    def pending(self) -> Any: ...


class UIAPI(Protocol):
    def show(self, value: Any) -> None: ...
    def t(self, key: str, default: str | None = None, **values: Any) -> str: ...
    def ask_text(self, prompt: str = "Text?", **options: Any) -> str | None: ...
    def ask_date(self, prompt: str = "Date?", **options: Any) -> date | None: ...
    def ask_time(self, prompt: str = "Time?", **options: Any) -> time | None: ...
    def ask_datetime(self, prompt: str = "Date/time?", **options: Any) -> datetime | None: ...
    def choose(self, title: str, items: Any, **options: Any) -> Any: ...
    def choose_many(self, title: str, items: Any, **options: Any) -> list[Any]: ...
    def confirm(self, text: str, **options: Any) -> bool: ...
    def choose_task(self, title: str | None = None, **filters: Any) -> Task | None: ...
    def choose_event(self, title: str | None = None, **filters: Any) -> Event | None: ...


class TemporalAPI(Protocol):
    def parse_date(self, text: str, *, bias: str = "any") -> date: ...
    def parse_datetime(self, text: str, *, bias: str = "any") -> datetime: ...
    def parse_time(self, text: str) -> time: ...


class CommandsAPI(Protocol):
    def run(self, name: str, *args: Any, **kwargs: Any) -> Any: ...
    def register_extension(
        self,
        name: str,
        handler: Callable[..., Any],
        *,
        extension: str | None = None,
        **options: Any,
    ) -> Any: ...
    def names(self, *, include_aliases: bool = False) -> tuple[str, ...]: ...


class ActivityAPI(Protocol):
    def today(self) -> list[Activity]: ...
    def for_task(self, task: Task | str) -> list[Activity]: ...
    def record(
        self,
        action: str,
        object_id: str | None = None,
        **metadata: Any,
    ) -> Activity: ...


class SettingsAPI(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> Any: ...
    def reset(self, key: str) -> Any: ...
    def describe(self, key: str) -> Mapping[str, Any]: ...
    def list(self, category: str | None = None) -> Sequence[Mapping[str, Any]]: ...


class SessionAPI(Protocol):
    last_items: list[Any]
    current_selection: Any

    def current_task_id(self) -> str | None: ...
    def current_task(self) -> Task | None: ...
    def paused_task_ids(self) -> tuple[str, ...]: ...
    def paused_tasks(self) -> list[Task]: ...


__all__ = [
    "TasksAPI",
    "EventsAPI",
    "AgendaAPI",
    "RemindersAPI",
    "NotificationsAPI",
    "WordPressAPI",
    "UIAPI",
    "TemporalAPI",
    "CommandsAPI",
    "ActivityAPI",
    "SettingsAPI",
    "SessionAPI",
]
