from typing import Protocol, Any
class KeyValueRepository(Protocol):
    def get(self, key: str, default: Any=None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def delete(self, key: str) -> None: ...
